name: tailor_made
description: Tailor-Made with love.
version: 1.2.0

environment:
  sdk: ">=2.6.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  firebase_auth: ^4.1.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  url_launcher: ^6.1.6
  rxdart: ^0.26.0
  flutter_masked_text2: ^0.9.1
  photo_view: ^0.14.0
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0
  google_sign_in: ^5.4.2
  get_version:
    git:
      url: https://github.com/Creky/get_version.git
  flutter_native_contact_picker: ^0.0.3
  version: ^3.0.2
  timeago: ^3.3.0
  flutter_native_image:
    git:
      url: https://github.com/btastic/flutter_native_image.git
  equatable: ^2.0.5
  rebloc: ^0.4.0
  injector: ^2.0.0
  uuid: ^3.0.6
  built_value: ^8.4.2
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^1.0.0
  build_runner: ^2.3.2
  built_value_generator: ^8.4.2
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
